const nodemailer = require("nodemailer");

let transporter;

function getTransporter() {
  if (!transporter) {
    const service = process.env.EMAIL_SERVICE || "gmail";

    if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
      throw new Error("EMAIL_USER and EMAIL_PASS must be configured.");
    }

    transporter = nodemailer.createTransport({
      service,
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
      },
    });
  }
  return transporter;
}

/**
 * Send the AI-generated summary to the recipient
 * @param {string} to - Recipient email
 * @param {string} summaryHtml - HTML content from Gemini
 * @param {string} filename - Original filename
 * @param {number} rowCount - Number of data rows
 * @param {string} requestId - Unique request ID
 */
async function sendSummaryEmail(to, summaryHtml, filename, rowCount, requestId) {
  const mailer = getTransporter();

  const emailHtml = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Sales Data Summary</title>
</head>
<body style="margin:0;padding:0;background:#f8fafc;font-family:'Segoe UI',Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f8fafc;padding:40px 0;">
    <tr>
      <td align="center">
        <table width="640" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.08);">
          <!-- Header -->
          <tr>
            <td style="background:linear-gradient(135deg,#0f172a 0%,#1e3a5f 100%);padding:36px 40px;">
              <h1 style="margin:0;color:#ffffff;font-size:24px;font-weight:700;letter-spacing:-0.5px;">
                📊 Sales Data Summary
              </h1>
              <p style="margin:8px 0 0;color:#94a3b8;font-size:14px;">
                Powered by AI Analysis
              </p>
            </td>
          </tr>

          <!-- Meta info -->
          <tr>
            <td style="padding:24px 40px;background:#f1f5f9;border-bottom:1px solid #e2e8f0;">
              <table width="100%">
                <tr>
                  <td style="font-size:13px;color:#64748b;">
                    <strong style="color:#334155;">File:</strong> ${filename}
                  </td>
                  <td style="font-size:13px;color:#64748b;text-align:right;">
                    <strong style="color:#334155;">Records:</strong> ${rowCount.toLocaleString()}
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- AI Summary Content -->
          <tr>
            <td style="padding:36px 40px;color:#1e293b;font-size:15px;line-height:1.7;">
              ${summaryHtml}
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="padding:24px 40px;background:#f8fafc;border-top:1px solid #e2e8f0;">
              <p style="margin:0;font-size:12px;color:#94a3b8;text-align:center;">
                Generated by Sales Summarizer &bull; Request ID: ${requestId}
              </p>
              <p style="margin:8px 0 0;font-size:11px;color:#cbd5e1;text-align:center;">
                This summary was automatically generated by AI. Please verify key figures with source data.
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;

  const info = await mailer.sendMail({
    from: `"Sales Summarizer" <${process.env.EMAIL_USER}>`,
    to,
    subject: `📊 Sales Summary: ${filename} (${rowCount} records)`,
    html: emailHtml,
    text: `Sales Summary for ${filename}\n\nPlease view this email in an HTML-capable client for the formatted summary.\n\nRequest ID: ${requestId}`,
  });

  return info;
}

/**
 * Verify email service connectivity
 */
async function verifyEmailService() {
  try {
    const mailer = getTransporter();
    await mailer.verify();
    return true;
  } catch {
    return false;
  }
}

module.exports = { sendSummaryEmail, verifyEmailService };
